### ISSUE TITLE
计算时间和硬件配置有关系吗？

### ISSUE THREAD

**Issue by Y80** [wcaptcha/wcaptcha-api#2]
会不会出现我用M1芯片的电脑，一秒就算出来了，别人用台五年前的电脑，起码三秒才算得出来。

**Comment by greensea** [comment]
是的，硬件配置会影响速度，不过这个速度差别还算可控。
计算的核心内容是连续的乘法和取模，乘法和取模都是非常简单的运算，在硬件上的实现几乎已经没有任何优化空间，这减少了硬件性能带来的影响。

此外，这个工作量证明算法是无法并行加速的，也就是说，多核 CPU 相对单核 CPU 来说没有特别的优势，速度只取决于单核的性能。

考虑到现在大部分人的 CPU 频率以及性能差距都不会很大，取一个比较中庸的难度即可，配置好一点的用户速度就快一点，配置差一点的用户速度就只能慢一点了，对于大部分用户来说这个速度差距应该能维持在最多三倍左右。

不过需要指出的是，似乎移动平台的处理器在计算的时候速度偏慢，但也能基本保持在 3 倍多左右的差距。下面是我自己做的一些测试，供参考。

模数长度 512 位，难度 2^22-1

```
平台                    | 速度
Ryzen 5 2600, Chrome   | 2.6s
Ryzen 5 2600, Firefox  | 2.4s
骁龙 765G, Chrome       | 9.7s
赛扬 1037U, Firefox     | 8.9s
```

**Comment by greensea** [comment]
补充一下，移动平台上的速度偏慢似乎是浏览器 WASM 实现的影响，我用原生程序测试的时候，Ryzen 2600 只比骁龙 765G 快了一倍多一点点
