### ISSUE TITLE
Vercel 部署失败

### ISSUE THREAD

**Issue by cf-pages** [wcaptcha/wcaptcha-api#3]
Error: Could not find an exported function in "api/web.go"
 Learn more: https://vercel.com/docs/runtimes#official-runtimes/go

看官方文档好像说需要export a function

`In order to use this Runtime, no configuration is needed. You only need to create a file inside the api directory.

The entry point of this Runtime is a global matching .go files that export a function that implements the http.HandlerFunc signature.`

**Comment by cf-pages** [comment]
#4 自己稍微改了下代码，虽然比较粗糙，但现在能够通过vercel部署过程中的检测了，可以正常部署了，遇到同样问题的可以参考

**Comment by greensea** [comment]
虽然我部署的时候没遇到这个问题，不过既然你已经改好了，我就直接合并然后关闭这个 issue 了
